# Generated by Django 4.0.3 on 2022-03-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_submissioncode_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('regdno', models.CharField(max_length=20)),
                ('submission', models.ManyToManyField(related_name='participant_submission', to='core.submissioncode')),
            ],
        ),
    ]
