# Generated by Django 4.0.3 on 2022-03-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_submissioncode_name_and_more'),
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='submission',
            field=models.ManyToManyField(blank=True, null=True, related_name='participant_submission', to='core.submissioncode'),
        ),
    ]
