# Generated by Django 4.0.3 on 2022-03-10 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
        ('core', '0002_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioncode',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='question.question'),
        ),
    ]
