# Generated by Django 4.0.3 on 2022-03-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
        ('core', '0003_submissioncode_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissioncode',
            name='name',
        ),
        migrations.RemoveField(
            model_name='submissioncode',
            name='regd_no',
        ),
        migrations.AddField(
            model_name='submissioncode',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='participant.participant'),
        ),
    ]
