# Generated by Django 4.0.3 on 2022-03-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
        ('core', '0004_remove_submissioncode_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioncode',
            name='grp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='group.group'),
        ),
    ]
