# Generated by Django 4.0.3 on 2022-03-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='usernam',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
