# Generated by Django 4.0.3 on 2022-03-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_question_usernam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='usernam',
            new_name='username',
        ),
    ]
