# Generated by Django 4.0.3 on 2022-03-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('question', '0004_rename_usernam_question_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='groups',
            field=models.ManyToManyField(related_name='question_groups', to='group.group'),
        ),
    ]
